'use client';
import { useEffect, useMemo, useState } from 'react';
type RecordItem = { id:string; name:string; maskedId:string; scoreChange:number; agency:string; district:string; province:string; verificationSource:string; sources:{file:string;page:number}[]; url:string };
const API='https://260816-karemairodnare.vercel.app/api/v1/records.json';
export default function Home(){
 const [records,setRecords]=useState<RecordItem[]>([]),[query,setQuery]=useState(''),[province,setProvince]=useState('ทั้งหมด'),[district,setDistrict]=useState('ทั้งหมด'),[agency,setAgency]=useState('ทั้งหมด'),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{fetch(API).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setRecords(d.records??[])).catch(()=>setError('ไม่สามารถโหลดข้อมูลได้ กรุณาลองใหม่อีกครั้ง')).finally(()=>setLoading(false))},[]);
 const provinces=useMemo(()=>[...new Set(records.map(r=>r.province))].sort(),[records]);
 const districts=useMemo(()=>[...new Set(records.filter(r=>province==='ทั้งหมด'||r.province===province).map(r=>r.district))].sort(),[records,province]);
 const agencies=useMemo(()=>[...new Set(records.filter(r=>(province==='ทั้งหมด'||r.province===province)&&(district==='ทั้งหมด'||r.district===district)).map(r=>r.agency))].sort(),[records,province,district]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('th');return records.filter(r=>{const text=`${r.name} ${r.maskedId} ${r.agency} ${r.district} ${r.province}`.toLocaleLowerCase('th');return(!q||text.includes(q))&&(province==='ทั้งหมด'||r.province===province)&&(district==='ทั้งหมด'||r.district===district)&&(agency==='ทั้งหมด'||r.agency===agency)})},[records,query,province,district,agency]);
 const size=20,total=Math.max(1,Math.ceil(filtered.length/size)),rows=filtered.slice((page-1)*size,page*size); const apply=(fn:()=>void)=>{fn();setPage(1)}; const reset=()=>{setQuery('');setProvince('ทั้งหมด');setDistrict('ทั้งหมด');setAgency('ทั้งหมด');setPage(1)};
 return <main><header className="topbar"><div className="brand"><span className="brand-mark">ท</span><div><strong>ทำเนียบข้อมูลสาธารณะ</strong><small>PUBLIC RECORDS DIRECTORY</small></div></div><a className="api-link" href="https://260816-karemairodnare.vercel.app/api" target="_blank" rel="noreferrer">API Documentation ↗</a></header>
 <section className="hero"><div className="hero-inner"><p className="eyebrow">ฐานข้อมูลสาธารณะ · อัปเดต 23 สิงหาคม 2569</p><h1>ค้นหารายชื่อ<br/><span>อย่างโปร่งใส</span></h1><p className="lede">สำรวจและตรวจสอบข้อมูลจากเอกสารเผยแพร่สาธารณะ ค้นหาได้ด้วยชื่อ จังหวัด อำเภอ และหน่วยงาน</p><div className="searchbox"><span>⌕</span><input aria-label="ค้นหารายชื่อ" placeholder="ค้นหาชื่อ เลขบัตร หน่วยงาน หรือพื้นที่..." value={query} onChange={e=>apply(()=>setQuery(e.target.value))}/><kbd>ค้นหา</kbd></div><div className="stats"><div><b>{records.length.toLocaleString('th-TH')}</b><span>รายชื่อทั้งหมด</span></div><div><b>{provinces.length||77}</b><span>จังหวัด</span></div><div><b>{new Set(records.map(r=>r.agency)).size.toLocaleString('th-TH')}</b><span>หน่วยงาน</span></div></div></div></section>
 <section className="content"><div className="section-head"><div><p className="eyebrow dark">ค้นหาแบบละเอียด</p><h2>รายชื่อในฐานข้อมูล</h2></div><span className="result-count">พบ {filtered.length.toLocaleString('th-TH')} รายการ</span></div><div className="filters"><label>จังหวัด<select value={province} onChange={e=>apply(()=>{setProvince(e.target.value);setDistrict('ทั้งหมด');setAgency('ทั้งหมด')})}><option>ทั้งหมด</option>{provinces.map(v=><option key={v}>{v}</option>)}</select></label><label>อำเภอ<select value={district} onChange={e=>apply(()=>{setDistrict(e.target.value);setAgency('ทั้งหมด')})}><option>ทั้งหมด</option>{districts.map(v=><option key={v}>{v}</option>)}</select></label><label>หน่วยงาน<select value={agency} onChange={e=>apply(()=>setAgency(e.target.value))}><option>ทั้งหมด</option>{agencies.map(v=><option key={v}>{v}</option>)}</select></label><button onClick={reset}>ล้างตัวกรอง</button></div>
 <div className="table-wrap">{loading?<div className="state">กำลังโหลดข้อมูล...</div>:error?<div className="state error">{error}</div>:!rows.length?<div className="state">ไม่พบข้อมูลที่ค้นหา</div>:<table><thead><tr><th>ชื่อ–นามสกุล</th><th>หน่วยงาน</th><th>พื้นที่</th><th>การเปลี่ยนแปลง</th><th>แหล่งข้อมูล</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><a href={r.url} target="_blank" rel="noreferrer"><strong>{r.name}</strong><small>{r.maskedId}</small></a></td><td>{r.agency}</td><td>{r.district}<small>{r.province}</small></td><td><span className="score">+{r.scoreChange}</span></td><td><span className="verified">✓ ตรวจสอบแล้ว</span><small>{r.sources[0]?.file} · หน้า {r.sources[0]?.page}</small></td></tr>)}</tbody></table>}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← ก่อนหน้า</button><span>หน้า {page.toLocaleString('th-TH')} จาก {total.toLocaleString('th-TH')}</span><button disabled={page===total} onClick={()=>setPage(p=>p+1)}>ถัดไป →</button></div></section>
 <aside className="notice"><b>ข้อควรทราบ</b><p>ข้อมูลนี้รวบรวมจากเอกสารที่เผยแพร่ต่อสาธารณะ ไม่ใช่การระบุสถานะทางคดี ความผิด หรือคำพิพากษา ชื่อที่คล้ายกันอาจเป็นคนละบุคคล โปรดตรวจสอบเอกสารต้นฉบับทุกครั้ง</p></aside><footer>ฐานข้อมูลเพื่อการเข้าถึงข้อมูลสาธารณะอย่างรับผิดชอบ <span>ข้อมูล {records.length.toLocaleString('th-TH')} รายการ</span></footer></main>
}
